on:
  push:
    branches:
    - maven-publish
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: ':22w13oneblockatatime:publishToMavenLocal -Ptype=snapshot'
    - run: 'find ~/.m2/repository/de/oceanlabs/mcp/mcp_config/ -print'
     