name: publish
on:
  push:
    branches:
    - maven-publish
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
    - uses: actions/checkout@v3
      with:
        ref: 'maven'
      id: checkout-maven
      continue-on-error: true
    - run: cp -r de/oceanlabs/mcp/mcp_config ~/.m2/repository/de/oceanlabs/mcp/mcp_config
      if: steps.checkout-maven.outcome == 'success'
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: ':22w13oneblockatatime:publishToMavenLocal -Ptype=snapshot'
    - run: find ~/.m2/repository/de/oceanlabs/mcp/mcp_config
     